### PR TITLE
create a separate project for every installation

### PR DESCRIPTION
**Pull request by pgerber**

### CODE REVIEW

**Comment by pgerber** [comment]
[rendered](https://pgerber-devops-docs.readthedocs.io/en/latest/openshift/create_nice_installation.html)

**Comment by osswald** [comment]
Is it really toco anderen not Rocco?

**Comment by osswald** [comment]
Tocco

**Comment by pgerber** [comment]
Yes, it is indeed. I assume VSHN just uses four-letter abbreviations for their customers, or it's simply a typo. Either way, less typing is a good thing.

**Comment by osswald** [comment]
It might be worth mentioning that fact somewhere

**Pull request merged**
